remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
title: UE WEB - 2020

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Enable or disable the site search
search_enabled: true

# # Aux links for the upper right navigation
# aux_links:
#   "Just the Docs on GitHub":
#     - "//github.com/pmarsceill/just-the-docs"


